networks:
  minha-rede:
    driver: overlay

services:
  fronttechpoints:
    image: edsonmorronogueira/fronttechpoints:latest
    ports:
      - "80:80"
    networks:
      - minha-rede

  backtechpoints:
    image: edsonmorronogueira/backtechpoints:latest
    environment:
      SERVER_PORT: 8080
      PASSWORD: password
      DB_HOST: mysql # Colocar o IP da EC2
      DB_PORT: 3306
      DB_NAME: techpointsdb
      DB_USER: user
      DB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      PASSWORD_EMAIL_SPRING: senha_email
    ports:
      - "8080:8080"
    networks:
      - minha-rede
      
  bdtechpoints:
    image: edsonmorronogueira/bdtechpoints:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_: mysql # Colocar o IP da EC2
      DB_PORT: 3306
      MYSQL_DATABASE: techpointsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - minha-rede
