networks:
  techpoints_network:
    external: true
    
services:
  fronttechpoints:
    build:
      context: ./front-end-arrastech
      dockerfile: Dockerfile
    container_name: fronttechpoints_container
    networks:
      - techpoints_network
    restart: on-failure
    depends_on:
      - backtechpoints
    ports:
      - "80:80"

  backtechpoints:
    build:
      context: ./back-end-arrastech/techPoints/techPoints
      dockerfile: Dockerfile
    container_name: backtechpoints_container
    environment:
      SERVER_PORT: 8080
      PASSWORD: password
      DB_HOST: "10.0.1.234" # Colocar o IP da EC2
      DB_PORT: 3306
      DB_NAME: techpointsdb
      DB_USER: user
      DB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      PASSWORD_EMAIL_SPRING: senha_email
    networks:
      - techpoints_network
    restart: on-failure
    ports:
      - "8080:8080"
